package reflect_test

import (
	"encoding/json"
	"fmt"
	"reflect"
	"testing"
	"strings"
)

type StructField struct {
	Name string
	Type string
	Tag  string
}

type StructDef struct {
	Name   string
	Fields []StructField
}

var structDefs []StructDef
var structCount = 0

func toCamel(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		parts[i] = strings.Title(parts[i])
	}
	return strings.Join(parts, "")
}

func inferType(value interface{}, name string) string {
	switch v := value.(type) {
	case string:
		return "string"
	case bool:
		return "bool"
	case float64:
		if float64(int64(v)) == v {
			return "int"
		}
		return "float64"
	case nil:
		return "interface{}"
	case map[string]interface{}:
		structName := toCamel(name)
		parseStruct(v, structName)
		return structName
	case map[interface{}]interface{}:
		// try to infer key/value types
		keyType, valType := "interface{}", "interface{}"
		for k, val := range v {
			keyType = reflect.TypeOf(k).String()
			valType = inferType(val, name+"Val")
			break
		}
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	case []interface{}:
		if len(v) == 0 {
			return "[]interface{}"
		}
		// assume homogeneous
		elemType := inferType(v[0], name+"Item")
		return "[]" + elemType
	default:
		return fmt.Sprintf("%T", v)
	}
}

func parseStruct(m map[string]interface{}, name string) {
	fields := []StructField{}
	for k, v := range m {
		typeStr := inferType(v, k)
		fields = append(fields, StructField{
			Name: toCamel(k),
			Type: typeStr,
			Tag:  fmt.Sprintf("`json:\"%s\"`", k),
		})
	}
	structDefs = append(structDefs, StructDef{Name: name, Fields: fields})
}

func generateStructs() string {
	var b strings.Builder
	for _, s := range structDefs {
		b.WriteString("type " + s.Name + " struct {\n")
		for _, f := range s.Fields {
			b.WriteString("\t" + f.Name + " " + f.Type + " " + f.Tag + "\n")
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func TestGenerateStructs(t *testing.T) {
	jsonData := `{
		"id": 123,
		"name": "Alice",
		"active": true,
		"scores": [95, 88, 76],
		"tags": ["go", "dev"],
		"profile": {
			"age": 30,
			"height": 1.75,
			"email": "alice@example.com"
		},
		"prefs": {"1": "on", "2": "off"},
		"notes": null
	}`

	var data map[string]interface{}
	_ = json.Unmarshal([]byte(jsonData), &data)
	parseStruct(data, "AutoGenerated")

	fmt.Println(generateStructs())
}
