<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit924a2be49be95a6b10d416a497e290dc
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'k' => 
        array (
            'kzmaster\\localLogger\\' => 21,
            'kzmaster\\firstLogger\\' => 21,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Ctype\\' => 23,
            'Symfony\\Component\\Yaml\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'kzmaster\\localLogger\\' => 
        array (
            0 => __DIR__ . '/..' . '/kzmaster2016/local-logger/src',
        ),
        'kzmaster\\firstLogger\\' => 
        array (
            0 => __DIR__ . '/..' . '/kzmaster2016/first-logger/src',
        ),
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit924a2be49be95a6b10d416a497e290dc::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit924a2be49be95a6b10d416a497e290dc::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit924a2be49be95a6b10d416a497e290dc::$classMap;

        }, null, ClassLoader::class);
    }
}
