<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'kzmaster\\localLogger\\' => array($vendorDir . '/kzmaster2016/local-logger/src'),
    'kzmaster\\firstLogger\\' => array($vendorDir . '/kzmaster2016/first-logger/src'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
);
